### ISSUE TITLE
Cannot run program on windows

### ISSUE THREAD

**Issue by ResourceHog** [MARUI-PlugIn/BlenderXR#10]
1 Open the sln in visual studio 2017

2 build the program.
3. this shows up.
![image](https://user-images.githubusercontent.com/3767092/47628015-b2b4ce00-daf0-11e8-9949-cc6879880188.png)

**Comment by pk15950** [comment]
That directory most likely doesn't exist on your machine, so you would have to change the output/debugging path in visual studio. The output directory was intended to dump into the folder of a built-from-source blender using the "make.bat" file from the blender source. 

However, the visual studio solution only builds the VR device dlls (i.e. BlenderXR_SteamVR.dll). To build the actual blender.exe you will need to run the "make.bat" file. More information on building blender from source can be found here: https://wiki.blender.org/wiki/Building_Blender/Windows
