### ISSUE TITLE
fixed

### ISSUE THREAD

**Issue by ghost** [MARUI-PlugIn/BlenderXR#11]

**Comment by pk15950** [comment]
Hi winsteadworks,
Thanks for your feedback and sorry about the issues. There's no need to install the libBlenderXR_SteamVR.so and libopenvr_api.so files as addons, so I would uninstall the UV: Magic UV addon. However, I don't believe that this is the problem.

Do you have SteamVR installed? Try starting SteamVR first and then clicking on "New VR Window" with SteamVR already running on the Vive.
