### ISSUE TITLE
notes on installation / question on threads

### ISSUE THREAD

**Issue by fornof** [MARUI-PlugIn/BlenderXR#13]
pthreads needed for cycles is version 2 in this build and version 3 in the svn downloaded libs. 
Solution is to either update the build to match or copy the v2 libs and rename to v3 , then copy into blender.exe directory. 

I also used Cmake-gui to turn off Collada since it was not found and was causing the build to fail.  The make.bat does not seem to have the feature to turn off collada. 

I ran into an issue with clearing the screen and screen lag : 
![firetrees](https://user-images.githubusercontent.com/1073801/50050399-eb1b6600-00b6-11e9-94dc-a4065c3efd50.jpg)
The screen lagged when lots of annotation verts were on the screen. 

Is this using one thread to pull the data from openvr into blender or separate threads ? 
It looks great. how did you send the window to the vr headset?

**Comment by pk15950** [comment]
Hi fornof, 
Sorry for the build issues. I realize that this is inconvenient but the build will likely not be updated to the latest Blender2.8 until the beginning of next month. In the meantime, you can use the old static dependencies to build from source: https://drive.google.com/file/d/1SZ9ENvZfsEaNyYypcE1OtPqb0g18VSBX/view.
I realize that this is a makeshift solution and apologize once again.

With respect to screen lag, yes the frame rate will drop considerably with many annotation vertices. We will work on improving this.

VR operations are integrated into the main Blender thread and are thus single-threaded. The window is "sent" to the VR headset by accessing the OpenGL device/context used by Blender and creating appropriate offscreen render buffers. These buffers are then used to blit the headset.
