### ISSUE TITLE
How do I change user scale?

### ISSUE THREAD

**Issue by guiglass** [MARUI-PlugIn/BlenderXR#16]
Is it possible to change the user scale in VR? 
In other words: 
If I have a 1:1 city scene, how would I scale myself to the size of godzilla?

Thanks.

**Comment by pk15950** [comment]
You can change the user scale by holding the "grip" buttons on both VR controllers and adjusting the distance between controllers to zoom in or out. This will not modify the transformations or scale of the scene objects.
