### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ghost** [MARUI-PlugIn/BlenderXR#17]
Here are a few suggestions for Blender XR

Add support to sculpt 

Add support for extrusions and cuts 

Add support to join and separate objects

Add support to record animations with Vive trackers 

Keep up the good work!

**Comment by pk15950** [comment]
Thanks (as always) for your feedback!
All of those features are on our todo list, and two of them will be released very soon.

**Comment by pk15950** [comment]
Hi winsteadworks, we just released a new version with the ability to perform extrusions and cuts and join and separate objects.

In case you can't find it, since it's a little hidden away, the "join" and "separate" operations are found in the tool settings menu of the "Add primitive" widget.

**Comment by ghost** [comment]
Nice! I will check it out when I get the chance. Looking forward to this

**Comment by AFE-GmdG** [comment]
It may be suitable to scale the world. If you view the default cube its way to big to work with it. Maybe by if you press both big buttons on the stick on the bottom of the HTC controller (i dont know the names of these buttons) the same time.

**Comment by max-krichenbauer** [comment]
Closing this issue because most (all?) of the features have already been implemented.
