### ISSUE TITLE
Humble suggestions

### ISSUE THREAD

**Issue by TheBricktop** [MARUI-PlugIn/BlenderXR#19]
Hey,
Thanks for marvellous work, BlenderXR is probably the only fleshed out full featured VR enabled editor ive found (that is free of course).

After some playing around with it Ive got some suggestions for UI : 

- Configurable UI palette would be awesome, cause sometimes Id rather rearrange some buttons for my workflow
- Additionally ALT button is very much neccesary for me 
- Snapping and mirror editing (and probably a special menu for modifiers, ike a floating window or sth) is a must for more precise work.
- less obstructive controllers maybe, more like only outline just like in sketchbox.
- on WMR selection using joystics is kinda unprecise, its very hard sometimest to quickly select some options because of joystic springing back and selecting an option near the one i wanted to select.
- the "no rotation other than Z" option for scaling and moving should be enabled by default.
- also I've managed to scale myself -1 on all axises making my eyes switch sides, so this is probably a bug

for now i model stuff traditionally and move stuff around in VR to get the feeling of space, but VR editor is the future.

**Comment by max-krichenbauer** [comment]
Hey,
Sorry for the late reply and thank you for your feedback!
Some of those are already on our to-do list.
I'll get back to you when we get around to implement them.
Best regards,
Max
