### ISSUE TITLE
Drivers for "generic" 3d modes

### ISSUE THREAD

**Issue by jaggzh** [MARUI-PlugIn/BlenderXR#24]
Is there support for a side-by-side mode, which can be used by anyone who can do the cross-their-eyes-method (3d stereograms)?

Also, I have a 3d tv (an old LG), it has support to convert side-by-side or vertical splits, in addition to a few other modes which would be more hardware-specific.

Here is an image of the 3d methods it provides (when connected via HDMI to my PC's old nvidia card -- less options are available when connected to other devices).  Also, note that one of the options is animated, showing side-by-side with alternating frames I believe:

![lg-tv-3d-modes](https://user-images.githubusercontent.com/20318973/60710182-f30dec80-9ec6-11e9-8fc6-2d0e13f179e2.jpg)

**Comment by max-krichenbauer** [comment]
Sorry for the late reply.
There is currently no support for non-VR stereo viewing.
We're not planning on adding this feature since the project is focused on VR support.
