### ISSUE TITLE
Merging Blender v2.80

### ISSUE THREAD

**Issue by sigmike** [MARUI-PlugIn/BlenderXR#29]
Hello,

I've been working on merging the final Blender v2.80 into BlenderXR. It's almost working: it builds and the VR window works, but the controllers are not visible (they work, I can interact with them, but I don't see them, nor their menu).

To make the merge I created a new repository with only the `blender` directory of BlenderXR and merged the v2.80 tag from the official Blender repository. So this repository contains the history of the `blender` part of BlenderXR, and the history of Blender.

What do you think about using such a repository instead of a plain copy in the `blender` directory? It could be a submodule, or just a separate repository. I think it would make future Blender merges much easier (just a pull from the official blender repository).

The repository is currently at https://github.com/sigmike/blender, with the last commit in the `xr-2.8` branch being the merge. It's a big merge, there has been a lot of changes in Blender since February, including a clang-format of all the source files (I formatted the `vr` files too, and moved the external VR libs to `/extern` so that they won't be formatted by `make format`).

About the invisible controllers, I'm not sure I'll be able to debug that. I'm not familiar enough with the Blender source code. Do you have a suggestion on how to fix that?

**Comment by sigmike** [comment]
I fixed the invisible controllers (https://github.com/sigmike/blender/commit/f7f4c42a71d5c69362d9ef0b757216accebf56f3). The code that updates the view matrix disappeared during the merge.

**Comment by max-krichenbauer** [comment]
Hi @sigmike ,
I'm really sorry for the late reply - it was a really busy week.

Great job on the Blender 2.8 merge. Sorry I could not respond in time to help out with the invisible controllers.
Is everything working well now or is there something else I could help with?

We're actually right now preparing a new release of BlenderXR with updated 2.8 source base and some new features and supported devices. But it might take a few more days to get everything online.

**Comment by sigmike** [comment]
Yes it seems to work well now.

Are you going to use a separate repository for Blender in this new release?

**Comment by max-krichenbauer** [comment]
No, this repository will will again be used for the new version.
