### ISSUE TITLE
build fails on fedora linux

### ISSUE THREAD

**Issue by hartsantler** [MARUI-PlugIn/BlenderXR#3]
i can build standard blender2.8 on my machine, so there must be something wrong in the cmake file for blenderXR

```
-- Found PNG: /usr/lib64/libpng.so (found version "1.6.34") 
-- Found Freetype: /usr/lib64/libfreetype.so (found version "2.8.0") 
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonLibsUnix (missing: PYTHON_LIBRARY PYTHON_LIBPATH
  PYTHON_INCLUDE_DIR PYTHON_INCLUDE_CONFIG_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  build_files/cmake/Modules/FindPythonLibsUnix.cmake:181 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  build_files/cmake/platform/platform_unix.cmake:82 (find_package)
  CMakeLists.txt:880 (include)

-- Configuring incomplete, errors occurred!
```

**Comment by hartsantler** [comment]
building on the latest linuxmint also fails, which also ships with python3.6

**Comment by pk15950** [comment]
Hi hartsantler,
Thanks for the feedback! Sorry for the build issues.
To build with python 3.6, you need to specify -DPYTHON_VERSION=3.6 when configuring with cmake. Also make sure that you have numpy installed.
If you encounter any other dependencies issues, you can probably resolve them by running the "install_deps.sh" script in /blender/build_files/build_environment.

**Comment by hartsantler** [comment]
thank you pk15950!
`-DPYTHON_VERSION=3.6` worked and i was able to compile the custom blender.
