### ISSUE TITLE
[BUG] Sculpting crash on a Oculus Rift while using a VR window

### ISSUE THREAD

**Issue by X-Calibar** [MARUI-PlugIn/BlenderXR#30]
On Windows 10 pro 64-bit, with Oculus Rift: I followed the steps provided https://www.marui-plugin.com/blender-xr/#download and downloaded from those links.  Program appears to work fine before opening a VR window including using the sculpt tool.  However, crashed to desktop upon using the sculpt tool in the VR window on a sphere.  (Also haven't figured out how to choose different sculpt options yet...)
In action: https://youtu.be/xoHUA8AUn5Q

Also was able to crash it when testing another tool on the sphere (knife?)

**Comment by max-krichenbauer** [comment]
Sorry for the delay. This was fixed with the new update to 2.81.
