### ISSUE TITLE
Vive Cosmos Controllers

### ISSUE THREAD

**Issue by sirkha** [MARUI-PlugIn/BlenderXR#32]
These work a lot like the Oculus touch controllers of the Rift-S/Quest era, but the grip is just a button.

**Comment by max-krichenbauer** [comment]
Can you please share the Prop_ManufacturerName_String, Prop_TrackingSystemName_String, and Prop_ModelNumber_String for the Cosmos so we can add it to the list?

See the source file for an example:
https://github.com/MARUI-PlugIn/BlenderXR/blob/a53b5a5db412c1d171a47842d8a1ef94d8bdbf5f/src/vr_steam.cpp#L342

**Comment by Joeyjordeson** [comment]
I have a Cosmos, how can i get these variables for you?

**Comment by max-krichenbauer** [comment]
Okay, to make it easier for people to report these variables, I updated the [BlenderXR_SteamVR.dll](https://github.com/MARUI-PlugIn/BlenderXR/blob/master/bin/Windows/SteamVR/BlenderXR_SteamVR.dll).
Please download the new version.
Then, when you start a new VR Window, a `DetectedDevices.log` file will be generated containing the values.

**Comment by Joeyjordeson** [comment]
ManufacturerName=HTC
TrackingSystemName=vive_eyes
ModelNumber=vive_cosmos

**Comment by max-krichenbauer** [comment]
New version
https://drive.google.com/file/d/1GvLqlYF2wwj7LIuxPThc0Le0A1K2Zn94/view?usp=sharing
and
https://github.com/MARUI-PlugIn/BlenderXR/blob/master/bin/Windows/SteamVR/BlenderXR_SteamVR.dll
adds support for Vive cosmos.
Please report here if it works for you.
