### ISSUE TITLE
New VR Window won't open

### ISSUE THREAD

**Issue by sither66** [MARUI-PlugIn/BlenderXR#33]
Hello MARUI Team,

I downloaded and unzipped the Blender XR window. I added the oculus.dll file (as I have an Oculus Rift). When I open up the Blender file that is inside of the BlenderXR file and click on New VR Window (under the Window tab) it flashes for a second but never opens the new VR window, it only stays on the main blender window. I have tried restarting my computer but to no success. I have also tried opening the window while my Oculus window (to ensure it wasn't the fault of my Oculus). 

What could be the cause of this issue? Is it a bug in the file? 

Please let me know. 

(I am very excited to start using blender in VR and what you guys are doing is paving the way for VR as a whole.

**Comment by max-krichenbauer** [comment]
Hallo,

Have you made sure to use the right way to download the file as described on the page: https://github.com/MARUI-PlugIn/BlenderXR/tree/master/bin/Windows/Oculus
In a word do **NOT** rlight-click-download-as, but click the "Download" button on the page.

Next, have you made sure that the Oculus Rift is attached to your PC and the Oculus App is installed and running?

**Comment by sither66** [comment]
Hello Max,


Yes I made sure to click the download button as instructed. I have followed the tutorial on the MARUI page step by step, along with other videos on YouTube of how to download MARUI. I carefully followed each step and get to the final step (opening New VR Window) and that's when the program seems to not want to open up. 

My Oculus is connected to my PC and I tried both without the Oculus window running and with, and even then it doesn't seem to work.

**Comment by max-krichenbauer** [comment]
Mhmm, that's strange.
Maybe you need to allow "unknown sources" in the Oculus App?

**Comment by sither66** [comment]
I already have the "unknown sources" tab checked. My computer is able to run VR at a steady rate. It is when I try to open the New VR window that it gets fussy. Have you any clue as to what else it could be? 


Thanks for the support.

**Comment by sither66** [comment]
Hello Max,

After all this time I am still having the same issue where the New VR Window doesn't want to open. Does Blender XR have to be used on a certain version of blender? Do I need specifically 2.8, 2.81 or 2.82? Please let me know. 

Thanks.

**Comment by max-krichenbauer** [comment]
You have to use the version of Blender that you can download at https://www.marui-plugin.com/blender-xr (Download -> Step1)

**Comment by naratteu** [comment]
i have same issue.
is it solved?

**Comment by sither66** [comment]
Not from since I tried.

**Comment by maestroC3** [comment]
When you plug your oculus in, your headset should ask you to “allow access to data “. After hitting “Allow” there should be a box in your oculus settings called “Oculus link” it should work after that.
