### ISSUE TITLE
 Edit Mode Switch with Valve Knuckles controllers

### ISSUE THREAD

**Issue by nagolinc** [MARUI-PlugIn/BlenderXR#34]
Neither pressing the touchpad nor pressing down on the joystick switches to edit mode.  I have also tried remapping other buttons to left_joystick_press and left_touchpad_press but still can't switch to edit mode.

I am similarly unable to do a Coordinate System Switch.

**Comment by max-krichenbauer** [comment]
Sorry for the delay.
I fixed the issue.
Please download the [BlenderXR_SteamVR.dll](https://github.com/MARUI-PlugIn/BlenderXR/raw/master/bin/Windows/SteamVR/BlenderXR_SteamVR.dll) again.

**Comment by nagolinc** [comment]
Awesome! Thanks!
