### ISSUE TITLE
Can not change camera view's properties when start VR Window

### ISSUE THREAD

**Issue by h3d-gianglt** [MARUI-PlugIn/BlenderXR#36]
I started a VR but i cant change Focal Length, Clip start and Clip end of the camera. when I edit the value, it reset to the origin value.

![image](https://user-images.githubusercontent.com/58353027/70528942-f6965580-1b81-11ea-9297-5612849cfb46.png)

**Comment by max-krichenbauer** [comment]
This is normal behavior because the camera's focal length, clip start and clip end control how you see the scene in VR and are updated automatically to match your headset (field of view) and zoom level.
