### ISSUE TITLE
New VR Window doesn't work with RiftCat through SteamVR

### ISSUE THREAD

**Issue by Kitsune-Ultima** [MARUI-PlugIn/BlenderXR#37]
The New VR Window doesn't want to open with RiftCat even though RiftCat uses the SteamVR api directly to connect to other VR programs without issue, is this a problem on your end or with the SteamVR api that RiftCat uses?

Note: RiftCat allows you to connect your phone, or a number of standalone VR headsets with your computer to use them as a headset for your computer.

**Comment by max-krichenbauer** [comment]
It might be a problem on the side of BlenderXR. What is the `Prop_ManufacturerName_String`, `Prop_TrackingSystemName_String` and `Prop_ModelNumber_String` of the device you're trying to use?

**Comment by artellblender** [comment]
I confirm the issue too, other VR apps works with SteamVR + Riftcat but Blender XR doesn't start.
Tested with Oculus Go.
Riftcat is an HTC Vive/Oculus Rift emulator for SteamVR.

**Comment by artellblender** [comment]
Where to find Prop_ManufacturerName_String, Prop_TrackingSystemName_String, and Prop_ModelNumber_String ?

**Comment by max-krichenbauer** [comment]
By calling `GetStringTrackedDeviceProperty()` on the SteamVR API.

Probably it's easiest to just run BlenderXR in a debugger and have it break at [line 307 of vr_steam.cpp](https://github.com/MARUI-PlugIn/BlenderXR/blob/c3241de98e9a325735506ee343973108f2510d6e/src/vr_steam.cpp#L307) and check the result.

Or you can contact the developers of RiftCat to just tell you.

**Comment by artellblender** [comment]
Thanks for the hint, being not familiar at all for the SteamVR API and not totally sure about how running BlenderXR in debug mode with SteamVR + Riftcat for the Oculus GO connection, i've just sent a message to the RiftCat team. If we can have it working i'll donate to this project for sure, thanks!

**Comment by artellblender** [comment]
The Riftcat team kindly replied to the inquiry, here is the message:

> We looked into it and some properties were not even listed. We'll add them and test it internally to make sure it doesn't break anything. If it doesnt, it iwll be included in the next update. You can find the list of properties below.

HMD:
Prop_ManufacturerName_String: "Riftcat"
Prop_TrackingSystemName_String: not set, might be changed to "vridge" in next update
Prop_ModelNumber_String: "Vridge"
Controller (generic)
Prop_ManufacturerName_String: not set, might be changed to "Riftcat" in next update
Prop_TrackingSystemName_String: not set, might be changed to "vridge" in next update
Prop_ModelNumber_String: "VridgeController"
Controller (oculus quest)
Prop_ManufacturerName_String: "Oculus"
Prop_TrackingSystemName_String: "oculus"
Prop_ModelNumber_String: "Oculus Rift CV1 (Left Controller)" / "Oculus Rift CV1 (Right Controller)"

**Comment by max-krichenbauer** [comment]
Thanks!
I added it. Please download the `BlenderXR_SteamVR.dll` again ( https://github.com/MARUI-PlugIn/BlenderXR/blob/master/bin/Windows/SteamVR/BlenderXR_SteamVR.dll - remember not to "right-click -> download link, but to open the link and press the download button).
Let me know if it works for you.

**Comment by artellblender** [comment]
Thank you, unfortunately it still doesn't start. Blender's console says "Failed to initialize VR".
However not sure if it's related to SteamVR, or we should wait for the next Riftcat version to include the changes?

**Comment by max-krichenbauer** [comment]
Well, they said "We'll add them and test it internally to make sure it doesn't break anything. If it doesnt, it iwll be included in the next update.", so, probably a few months to never, given that Oculus Go is obsolete and Oculus Link makes RiftCat obsolete.
I added a temporary work-around so that you can finally get to use BlenderXR. Please re-download `BlenderXR_SteamVR.dll` again.

**Comment by artellblender** [comment]
Thanks for your help. Unfortunately, same result here. But maybe it's just not possible, Blender is not a regular VR game so this may be reason why it doesn't work with Riftcat. I tried to automatically launch the VR window on Blender startup by script, but it still fails. It would have been fun to experience Blender with the Oculus Go, but anyway it would not be possible to make serious work with it since there is no spatial sensors. If it's too much of a problem it's best to give it up.

**Comment by max-krichenbauer** [comment]
Personally, I don't own RiftCat nor an Oculus Go, so I don't mind and I don't know how many people are interested in this feature.
I've been working it for you because you mentioned you donated to BlenderXR development.
