### ISSUE TITLE
Sculpting Pointer stays in a fixed location

### ISSUE THREAD

**Issue by nagolinc** [MARUI-PlugIn/BlenderXR#38]
When sculpting in VR, the point being drawn does not update as I move the controller (using SteamVR+Valve Index controllers).  This means it's possible to add a blob onto an object being sculpted but not to draw a smooth curve.

Created a video to show difference from sculpting using non-vr input:
https://youtu.be/gQnZSGybfEk

**Comment by dallytaur** [comment]
Same issue just downloaded it an hour ago and killing it for me

win10 HTC vive steam VR downloaded the latest build from time of writing might  try an older version and report back

edit: I couldn't find a build that had sculpting tools sadly

**Comment by max-krichenbauer** [comment]
Fixed in the new version (2.81).

**Comment by nagolinc** [comment]
Awesome! Thanks so much!

**Comment by dallytaur** [comment]
Has the new build been posted?

**Comment by nagolinc** [comment]
@mindlux The build on https://www.marui-plugin.com/blender-xr/ looks like it's still 2.80, but I was able to build from source by following these instructions:
https://github.com/MARUI-PlugIn/BlenderXR/blob/master/README.md
https://wiki.blender.org/wiki/Building_Blender/Windows

Here's a link to my build for SteamVR on Windows:
https://drive.google.com/open?id=1BPuM31l-ffmPNpNY1o3xs7UkuYsVsuFX

**Comment by max-krichenbauer** [comment]
That's strange, the link on https://www.marui-plugin.com/blender-xr/ should already have been updated.
I'll check. Anyhow, here's the new link:
https://drive.google.com/file/d/15boTamti_xs9G-JFyKO0Goqx0AaULhEH/view?usp=sharing
