### ISSUE TITLE
prebuilt linux binary fails on fedora linux

### ISSUE THREAD

**Issue by hartsantler** [MARUI-PlugIn/BlenderXR#4]
the linux download from https://www.marui-plugin.com/blender-xr/
requires python3.7, but fedora ships with python3.6

```
./blender: error while loading shared libraries: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by pk15950** [comment]
Thanks for the feedback!
We're currently working on building a more "portable" version of the prebuilt binary so please wait a little longer.

**Comment by pk15950** [comment]
The linux binary has been rebuilt with static dependencies so system python versions shouldn't matter anymore. Please give it another try if you get the chance.
