### ISSUE TITLE
Not recognizing CUDA capability

### ISSUE THREAD

**Issue by ubergeekseven** [MARUI-PlugIn/BlenderXR#40]
I have everything working correctly for oculus and I can enter vr fine. I went to change the preferences and add plugins after testing and I cannot enable cuda for rendering. Ihave an rtx 2070 and I am running with studio drivers. The other blender builds do load the cuda setting, anyone else have this issue? Should I just use this build for scene setup and then transfer to another build to render?

**Comment by max-krichenbauer** [comment]
Sorry for the late response.
For some reason, our build is missing the `2.81/scripts/addons/cycles/lib` folder.
We're trying to figure out why it's missing - it's not a part of the Blender build process that should have been affected by the added VR functionality - but there's a simple solution you can use:
just copy the folder with it's content from ["normal" Blender](https://www.blender.org/download/Blender2.81/blender-2.81a-windows64.zip/) to the VR Blender folder.

**Comment by ubergeekseven** [comment]
Nice, thanks for the feedback. Super simple fix and excited to play around again.
