### ISSUE TITLE
Blender XR hangs loading forever with Oculus Quest and Link to PC

### ISSUE THREAD

**Issue by antoniobernacchi** [MARUI-PlugIn/BlenderXR#42]
Hi,
Thank you very much for your work, I’m quite new to both blender and to VR, but it seems to be a paradigm shift and being able to jump inside blender models is just incredible.

I have a new Oculus Quest, connected to the PC through the beta feature Oculus Link, so that it acts like a Rift S.

It all works fine with other software, including Steam VR, but when opening a new Blender XR VR window it just gets stuck in loading ( a window of a new starting app shows up with the only message ‘loading....’ and no icon/image, it seems to have the icon of a missing referenced image actually, but when I move back to oculus home menu controller then blender icon appers in the loading window, but it still keeps hanging forever).

I tried both with the oculus dll and later changing that for the steamVR dlls and I run in the same issue (a window of startup shows up in steam and keeps loading forever).

Is it just working with the Rift and not with the linked Quest, or there is something that I might do wrong?

Thank you,

**Comment by antoniobernacchi** [comment]
I think the problem was related to my Nvidia Drivers, with the latest update released yesterday (442.19 Game) it's finally working (I use Oculus Quest connected through Link and the Rift dll).

Thanks so much to the development team,
It's just amazing!

**Comment by max-krichenbauer** [comment]
Sorry for the lack of response and thank you for writing the solution to the issue!
Glad you like BlenderXR!
