### ISSUE TITLE
ECOnomical question . . . 

### ISSUE THREAD

**Issue by inventadero** [MARUI-PlugIn/BlenderXR#43]
Hi! 
Excuse me:
Does it works only with Base Station + Controllers or the Head-set is needed?

Only want to trace drawig in the space . . . but looking at the regular screen.
I use GNU-Linux ( looking for 2nd hand HTC vive but headsets are expensive : /

Thanke Ü 
Congrats 4 the great work
~ ~ ~

**Comment by max-krichenbauer** [comment]
Hi!
You *always* need a headset to use the HTC base stations and controllers, not just for BlenderXR but for all software. As far as I know, there is no way to use the base station and controllers without the headset.
