### ISSUE TITLE
VR window closes instantly with ALVR

### ISSUE THREAD

**Issue by harigebaby** [MARUI-PlugIn/BlenderXR#44]
I don't know wether this issue is known but whenever I try to use this plugin with ALVR the window instantly closes. Just like riftcat, ALVR makes steam think it's dealing with an HTC vive headset. All steam games work just fine but for some reason blender XR doesn't. The window instantly closes.

I use oculus quest > alvr > steam

As I am not very familiar with anything that has to do with coding I don't know what information I should include...

**Comment by max-krichenbauer** [comment]
Why don't you just use Oculus Link?
I don't have ALVR. If you want support added, I need the Prop_ManufacturerName_String, Prop_TrackingSystemName_String and Prop_ModelNumber_String that the device exposes through SteamVR. Please see #37 for reference.

**Comment by stephenc87** [comment]
I can't rebuild for debug because the vc14 are no longer available
I am having the exact same issue, and Oculus Link requires a cable
I am happy to provide more information
