### ISSUE TITLE
When clicking "new VR window" the window will not open

### ISSUE THREAD

**Issue by ResourceHog** [MARUI-PlugIn/BlenderXR#45]
The window will briefly open then close itself.

**Comment by max-krichenbauer** [comment]
Support is only provided to people who support the project
https://www.patreon.com/BlenderXR

**Comment by ResourceHog** [comment]
For those in the future, The website is wrong. The answer is that HTC Vive has two sets of files that need to be in the same folder as the blender.exe file:

- libopenvr_api.so
- libBlenderXR_SteamVR.so
- openvr_api.dll
- BlenderXR_SteamVR.dll

The .so is important. Also make sure there isn't any (x) at the end of the filename where "x" is a number. A name like BlenderXR_SteamVR (1).dll might mess it up.
