### ISSUE TITLE
Support for Multiplayer

### ISSUE THREAD

**Issue by wprojects** [MARUI-PlugIn/BlenderXR#46]
Blender XR would be revolutionary if people could work together in a virtual space and build things together. I know this wouldn't be an easy task at the least, but it would be well worth your time. Imagine the things that would be possible if you allowed people to connect together in a virtual space and work on models remotely. It would be great if you could see the other persons headset or avatar and controllers in the virtual environment, and then network anything created between the devices that are connected in that space. This would change the game for VR 3D Modeling and Design. 

Also, 
Vive tracker support for creating animations would be awesome!
-- -- -- -- -- -- --
WW

**Comment by max-krichenbauer** [comment]
Thank you for your message.
If you enjoy BlenderXR please consider supporting the project:
https://www.patreon.com/BlenderXR
This helps us pay for hosting and development expenses.

Sorry, but we can't provide personal support to people who don't support BlenderXR right now.
There are simply too many requests from people who refuse to support us.
