### ISSUE TITLE
Mouse&Keyboard navigation

### ISSUE THREAD

**Issue by gaepard** [MARUI-PlugIn/BlenderXR#47]
Hi, 
   I've managed to run my Oculus Rift DK2 on your great VR Blender version, so awesome! :)
I don't have any controllers for my DK2 though.. is there any possibility to navigate through the Blender scene using mouse and/or keyboard? Perhaps something like a Blender fly or walk mode?
Thank a lot for your great work. I'll reflect my gratitude by donating ;)
Cheers!

**Comment by max-krichenbauer** [comment]
Thank you for your message.
If you enjoy BlenderXR please consider supporting the project:
https://www.patreon.com/BlenderXR
This helps us pay for hosting and development expenses.

Sorry, but we can't provide personal support to people who don't support BlenderXR right now.
There are simply too many requests from people who refuse to support us.
