### ISSUE TITLE
'New VR Window' doesnt open/crashes immediately (video).

### ISSUE THREAD

**Issue by Nostromo964** [MARUI-PlugIn/BlenderXR#49]
Trying to get this up and running with my Rift but for some reason when i try opening the VR window it looks like it opens for a second then immediately crashes (attached video).  Followed the steps in the video, not sure if i had to do anything else? 

[VRwindow_notworking.zip](https://github.com/MARUI-PlugIn/BlenderXR/files/4678924/VRwindow_notworking.zip)

**Comment by max-krichenbauer** [comment]
Thank you for your message.
If you enjoy BlenderXR please consider supporting the project:
https://www.marui-plugin.com/blender-xr/#support
https://www.patreon.com/BlenderXR
This helps us pay for hosting and development expenses.

Sorry, but we can't provide personal support to people who don't support BlenderXR right now.
There are simply too many requests from people who refuse to support us.
