### ISSUE TITLE
Failed to initialize VR. - VIVE

### ISSUE THREAD

**Issue by hgabor47** [MARUI-PlugIn/BlenderXR#52]
I have a VIVE VR headset. This working with SteamVR (1.13.10) I can play all VR games right.
When I click the 'New VR Window' menu I got  "Failed to initialize VR." message.
I copied the neccessary DLLs.

What can I do?
Thanks, Gabor
![blenderxr](https://user-images.githubusercontent.com/1212585/87596482-82f89000-c6f0-11ea-832d-1dd94acfa2f6.jpg)

**Comment by max-krichenbauer** [comment]
Have you followed the Readme when downloading the BlenderXR_SteamVR.dll and openvr_api.dll?

**Comment by hgabor47** [comment]
I think yes. 
Step 2.
Step2. Click and download the library for your VR device and place it in the Blender folder (next to the blender.exe).
https://github.com/MARUI-PlugIn/BlenderXR/tree/master/bin/Windows/SteamVR

After this message I changed the openvr_api from my SteamVR folder but no any effect.

**Comment by max-krichenbauer** [comment]
I mean the Readme on that page where you downloaded the DLLs:

> Warning!
> 
> Do NOT right-click and "save-as" the .DLL file! (You are only saving the download website if you do that).
> 
> Instead, click on the file name link to get to the download website, and on the download website click "Download".

Why did you change the openvr_api in your SteamVR folder?
The instruction is to **place it in the Blender folder (next to the blender.exe)**

**Comment by hgabor47** [comment]
Hi thanks,
I think I!m right but I found a LOG file with this content:

ManufacturerName=Pimax VR, Inc.
TrackingSystemName=aapvr
ModelNumber=Pimax 5K Plus

My model a PIMAX 5k and this is correct, but if the DLL not recognised this maybe this is a problem.
This model HTC VIVE compatible and all games recognised to VIVE.

**Comment by max-krichenbauer** [comment]
Thanks, that might explain it.
I updated and re-uploaded the BlenderXR_SteamVR.dll 
Please download it again and try again.

**Comment by hgabor47** [comment]
Thanks max! Working well now :)
