### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by molecule** [MARUI-PlugIn/BlenderXR#60]
Could someone help me understand what's happening in these lines:

https://github.com/MARUI-PlugIn/BlenderXR/blob/82512c51b028b3a17175a9eb3f3a673bcdad2b72/src/vr_steam.cpp#L855-L858

It looks like it's a strange kind of matrix manipulation, but not quite a clean transpose.

(Also curious if this project is still active?)
Thanks so much.

**Comment by SpaceArchitecture** [comment]
Hello,
Here's what I got from one of the team members :
"BlenderXR is deprecated.
If you want to use Blender in VR, please use the VR viewer in Blender itself.

If you are interested in the project, you can get the source code on github:
[https://github.com/MARUI-PlugIn/BlenderXR](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMARUI-PlugIn%2FBlenderXR&data=05%7C01%7C%7Cabd33ba2fe9b47854d3308da2c7ce714%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637871212218568231%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=H0eZcdA0DxPdxQw7Tw9VhhiUTjOC7dH2c5L5qM%2BAZHQ%3D&reserved=0)

Best regards,
Max"

**Comment by max-krichenbauer** [comment]
It's a change between coordinate systems between the VR device and Blender.
