### ISSUE TITLE
Is this project still alive ?

### ISSUE THREAD

**Issue by SpaceArchitecture** [MARUI-PlugIn/BlenderXR#61]
I suppose it's dead but it would be nice to know

**Comment by max-krichenbauer** [comment]
This project is no longer under development on our side, since Blender itself now offers VR viewing and there was no interest from the community to continue BlenderXR separately.
But the source code is here so you're free to pick up development.

**Comment by SpaceArchitecture** [comment]
Will do, can’t believe that there was no interest from the community, would you be ready to accept a paid project ?

 

Thomas Lagarde

 

 <https://www.linkedin.com/in/thomas-lagarde-b8866549> Linkedin

 <https://www.researchgate.net/profile/Thomas_Lagarde> Projects

 <https://spacearchitecture.fr/> Website
