### ISSUE TITLE
I can't use

### ISSUE THREAD

**Issue by onerisgf** [MARUI-PlugIn/BlenderXR#62]
I downloaded the Repository, I tried builder with VS, I also tried to put the files in the blender folder, I also tried with builder "make", but nothing works for me to have the root folder and be able to access it with my VR . Can someone please teach me in a clearer way how I can have the root folder and be able to run on my machine?

**Comment by max-krichenbauer** [comment]
Please read the documentation
https://github.com/MARUI-PlugIn/BlenderXR/wiki
