### ISSUE TITLE
There is no way to open a new vr window in blender 2.8

### ISSUE THREAD

**Issue by ResourceHog** [MARUI-PlugIn/BlenderXR#9]
![image](https://user-images.githubusercontent.com/3767092/47626116-bba0a200-dae6-11e8-9869-9afb456f47d4.png)
![image](https://user-images.githubusercontent.com/3767092/47626148-ebe84080-dae6-11e8-86cb-f27794a856e8.png)

Did I install the dll's incorrectly?

**Comment by ResourceHog** [comment]
Doing some research I found [this](https://stackoverflow.com/questions/43387657/how-to-use-opencv-c-code-in-blender/43405401). Apparently you can't use C++ as an ad-don for blender?

**Comment by ResourceHog** [comment]
A confirmed problem in 2.79 as well.
![image](https://user-images.githubusercontent.com/3767092/47627540-e3473880-daed-11e8-9de1-ad1ba6dea41c.png)

**Comment by pk15950** [comment]
Hi ResourceHog,
In order to use BlenderXR, you must use the custom-built Blender 2.8 available here: https://www.marui-plugin.com/blender-xr/
Or, you can build the executable yourself using the source code provided in the "blender" folder in this repository.
